[language-servers]
"marksman" = { command = "marksman", args=["server"] }

[[language]]
name = "c"
indent = { tab-width = 1, unit = "    " }

# Use marksman: https://github.com/artempyanykh/marksman
[[language]]
name = "markdown"
scope = "source.md"
injection-regex = "md|markdown"
file-types = ["md"]
roots = [".marksman.toml"]
language-servers = ["marksman"]
indent = { tab-width = 2, unit = " " }

[[language]]
name = "go"

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'

